# Generated by Django 4.0.3 on 2022-04-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='NikeName',
            new_name='nikename',
        ),
    ]
