# Generated by Django 4.0.3 on 2022-04-13 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0003_userinfo_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fan_number',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='focus_number',
            field=models.IntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_suppper_user',
            field=models.BooleanField(default=False, verbose_name='超级用户'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='createtime',
            field=models.DateField(default=datetime.date.today, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nikename',
            field=models.CharField(max_length=64, verbose_name='昵称'),
        ),
    ]
