# Generated by Django 4.0.3 on 2022-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0004_userinfo_fan_number_userinfo_focus_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='head_image_url',
            field=models.ImageField(default='/head_img/default.jpg', upload_to='head_img', verbose_name='头像'),
        ),
    ]
