# Generated by Django 4.0.3 on 2022-04-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0005_userinfo_head_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='head_image_url',
            new_name='head_image',
        ),
    ]
