# Generated by Django 4.0.3 on 2022-04-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0006_rename_head_image_url_userinfo_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='createtime',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
