# Generated by Django 4.0.3 on 2022-04-17 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_search', '0007_alter_userinfo_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帐号'),
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=64, verbose_name='图片名称')),
                ('image', models.ImageField(upload_to='head_img', verbose_name='图片路径')),
                ('createtime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('like_number', models.IntegerField(db_index=True, default=0, verbose_name='点赞数')),
                ('store_number', models.IntegerField(db_index=True, default=0, verbose_name='收藏数')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帐号')),
            ],
            options={
                'index_together': {('username', 'createtime')},
            },
        ),
    ]
