# Generated by Django 4.0.3 on 2022-04-17 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_search', '0008_alter_userinfo_user_imageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='describe',
            field=models.CharField(default='', max_length=100, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帐号'),
        ),
    ]
