# Generated by Django 4.0.3 on 2022-04-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0009_imageinfo_describe_alter_imageinfo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
