# Generated by Django 4.0.3 on 2022-04-21 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0010_alter_imageinfo_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahash', models.CharField(max_length=100, verbose_name='均值哈希')),
                ('dhash', models.CharField(max_length=100, verbose_name='差值哈希')),
                ('phash', models.CharField(max_length=100, verbose_name='感知哈希')),
                ('whash', models.CharField(max_length=100, verbose_name='小波哈希')),
                ('createtime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('imageinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_search.imageinfo', verbose_name='图片信息')),
            ],
        ),
    ]
