# Generated by Django 4.0.3 on 2022-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0011_imagefp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='head_image',
            field=models.ImageField(default='/head_img/default.jpeg', upload_to='head_img', verbose_name='头像'),
        ),
    ]
