# Generated by Django 4.0.3 on 2022-04-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0014_userinfo_hobby_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='hobby_tag',
            field=models.CharField(default='', max_length=512, verbose_name='兴趣标签'),
        ),
    ]
