# Generated by Django 4.0.3 on 2022-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0015_alter_userinfo_hobby_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='score',
            field=models.DecimalField(db_index=True, decimal_places=10, max_digits=11, verbose_name='分数'),
        ),
    ]
